{% set version = "2.5.2" %}

package:
  name: nb_conda_kernels
  version: {{ version }}

source:
  url: https://github.com/anaconda/nb_conda_kernels/archive/{{ version }}.tar.gz
  sha256: f987a852e077eeed3614b9cc16012ba3f2be52a5e8eb07a2191ad9975b282178

build:
  number: 2

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - jupyter_client >=4.2
    - jupyter_core
    # traitlets isn't mentioned in requirements
    # but it's used here https://github.com/anaconda/nb_conda_kernels/blob/2.5.0/nb_conda_kernels/manager.py#L14
    - traitlets
    - psutil
    - notebook >=5.3.0

test:
  imports:
    - nb_conda_kernels
  source_files:
    - setup.cfg
    - tests
  requires:
    - pip
    - pytest
    - ipykernel
    - notebook
    - requests
    - mock
  commands:
    - pip check
    - test -f ${PREFIX}/bin/.nb_conda_kernels-post-link.sh   # [unix]
    - test -f ${PREFIX}/bin/.nb_conda_kernels-pre-unlink.sh  # [unix]
    - if not exist %PREFIX%\Scripts\.nb_conda_kernels-post-link.bat (exit 1)   # [win]
    - if not exist %PREFIX%\Scripts\.nb_conda_kernels-pre-unlink.bat (exit 1)  # [win]
    - python -m nb_conda_kernels list
    # Set JUPYTER_PLATFORM_DIRS to disable DeprecationWarning
    - set JUPYTER_PLATFORM_DIRS=1      # [win]
    - export JUPYTER_PLATFORM_DIRS=1   # [unix]
    - jupyter --paths
    # Skips any tests that assume the existence of the testbed
    - python -m pytest -v -m "not testbed" tests --disable-pytest-warnings

about:
  home: https://github.com/anaconda/nb_conda_kernels
  summary: Package for managing conda environment-based kernels inside of Jupyter
  description: |
    This extension enables a Jupyter Notebook or JupyterLab application
    in one conda environment to access kernels for Python, R,
    and other languages found in other environments"
  dev_url: https://github.com/anaconda/nb_conda_kernels
  doc_url: https://github.com/anaconda/nb_conda_kernels
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Launch Jupyter kernels for any installed conda environment

extra:
  recipe-maintainers:
    - mcg1969
    - bkreider
