{% set version = "2.0.0" %}
{% set gh_org = "Anaconda-Platform" %}
{% set gh_repo = "nb_conda_kernels" %}

package:
  name: {{ gh_repo }}
  version: {{ version }}

source:
  fn: {{ gh_repo }}-{{ version }}.tar.gz
  url: https://github.com/{{ gh_org }}/{{ gh_repo }}/archive/{{ version }}.tar.gz
  sha256: 738dab837fbc2ba515c91d64bf84486361913caae9fd9479933919973c215405

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - notebook >=4.2.0
    - python

test:
  source_files:
    - nb_conda_kernels
  requires:
    - coverage
    - flake8
    - nodejs
    - nose
    - notebook >=4.2.0
    - python
    - requests
    - mock  # [py2k]
  imports:
    - nb_conda_kernels

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Launch Jupyter kernels for any installed conda environment.'

extra:
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
