{% set version = "2.5.0" %}

package:
  name: nb_conda_kernels
  version: {{ version }}

source:
  url: https://github.com/Anaconda-Platform/nb_conda_kernels/archive/{{ version }}.tar.gz
  sha256: c306ec3db5188ee48493cee717667486592e696fb9aa8ed9041c40cf4e3ddfe5

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.6
    - jupyter_client >=4.2
    - jupyter_core
    - psutil
  run_constrained:
    - notebook >=5.3.0

test:
  source_files:
    - setup.cfg
    - tests
  requires:
    - pip
    - pytest
    - pytest-cov
    - ipykernel
    - notebook <7
    - requests
    - mock
  commands:
    - pip check
    - python -m nb_conda_kernels list
    - python -m pytest -v --cov=nb_conda_kernels tests

about:
  home: https://github.com/Anaconda-Platform/nb_conda_kernels
  summary: "This extension enables a Jupyter Notebook or JupyterLab application in one conda environment to access kernels for Python, R, and other languages found in other environments"
  description: "This extension enables a Jupyter Notebook or JupyterLab application in one conda environment to access kernels for Python, R, and other languages found in other environments"
  dev_url: https://github.com/anaconda/nb_conda_kernels
  doc_url: https://github.com/anaconda/nb_conda_kernels
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Launch Jupyter kernels for any installed conda environment

extra:
  skip-lints:
    - avoid_noarch
    - missing_imports_or_run_test_py

  recipe-maintainers:
    - mcg1969
    - bkreider
