{% set version = "2.5.0" %}

package:
  name: nb_conda_kernels
  version: {{ version }}

source:
  url: https://github.com/Anaconda-Platform/nb_conda_kernels/archive/{{ version }}.tar.gz
  sha256: c306ec3db5188ee48493cee717667486592e696fb9aa8ed9041c40cf4e3ddfe5

build:
  number: 0

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - jupyter_client >=4.2
    - jupyter_core
    - jupyter_server
    # traitlets isn't mentioned in requirements
    # but it's used here https://github.com/anaconda/nb_conda_kernels/blob/2.5.0/nb_conda_kernels/manager.py#L14
    - traitlets
    - psutil
  run_constrained:
    - notebook >=5.3.0,<7

test:
  imports:
    - nb_conda_kernels
  source_files:
    - setup.cfg
    - tests
  requires:
    - pip
    - pytest
    - pytest-cov
    - ipykernel
    - notebook <7
    - requests
    - mock
  commands:
    - pip check
    - test -f ${PREFIX}/bin/.nb_conda_kernels-post-link.sh   # [unix]
    - test -f ${PREFIX}/bin/.nb_conda_kernels-pre-unlink.sh  # [unix]
    - if not exist %PREFIX%\Scripts\.nb_conda_kernels-post-link.bat (exit 1)   # [win]
    - if not exist %PREFIX%\Scripts\.nb_conda_kernels-pre-unlink.bat (exit 1)  # [win]
    - python -m nb_conda_kernels list
    - set PYTHONIOENCODING=UTF-8       # [win]
    - export PYTHONUNBUFFERED=1        # [unix]
    # Set JUPYTER_PLATFORM_DIRS to disable DeprecationWarning
    - set JUPYTER_PLATFORM_DIRS=1      # [win]
    - export JUPYTER_PLATFORM_DIRS=1   # [unix]
    - jupyter --paths
    # Skip test_configuration because it seems to be broken.
    - pytest -vvv tests -k "not test_configuration" --disable-pytest-warnings

about:
  home: https://github.com/Anaconda-Platform/nb_conda_kernels
  summary: Package for managing conda environment-based kernels inside of Jupyter
  description: |
    This extension enables a Jupyter Notebook or JupyterLab application
    in one conda environment to access kernels for Python, R,
    and other languages found in other environments"
  dev_url: https://github.com/anaconda/nb_conda_kernels
  doc_url: https://github.com/anaconda/nb_conda_kernels
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Launch Jupyter kernels for any installed conda environment

extra:
  recipe-maintainers:
    - mcg1969
    - bkreider
