# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TDZAnTsgWd3krs35b9d+iy0RBG3u1QtiLElN9p/PJgX4rfdY7UkpoDYTII587mvHxdFNCCm7I3/HzccKC3hYfKmSwRWf4rOqhVlz4yl6w9yIL3shHw6UsQ3agIpNYLkNAkFbMb5u0tb/2Eja+78Zg9JEN0SNSfmHaoQfD9BlYgKHA+B/TYmSG5B3RmVl8GAtnpPFJPwUErDClXbXZ918oCXqgX3d9YT9kt9o1adR763vHQD3IfAtHZ8Bg3ynwAUJCP1q3g5TfUmutMJGdlIjyrxFspMvij7b8rsNGHaBuUPKzKJTwFkf9chymhBjiXL8knogTyOk6GdFBa+8efoVVM/ou0ouBZHgGtp9bWTr9n4yDhz91xUHHFMuIXZuaBdgfUA41kWhkwy3rgZVQsZQPjmpjsw/vFv65Vrv3GaKzLzPjSG80MNbSsnX9/TgBsFAovXb1SxJJK0qMFaoWoCPDJWPwZoVpDOmfelI4BsmwNBJjjmXPsv1o+78qvNGXzs0SOJDdtTVZdEnS5OPak2e5Lo6k6QwQx8rTfxi8vt0HTA+wTY1oYNfiwM8eYzX+iigTOEPGi/NEO9ByeC/fKHaXXPB/hYs1gSwWnjj+9Bgze90meL8lmoeRwPiLTrfetVtTSYLa+6KPjhiYvIgxRgKpDnS1rp6IzNlW9PiCjeGJQI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
