appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TDZAnTsgWd3krs35b9d+iy0RBG3u1QtiLElN9p/PJgX4rfdY7UkpoDYTII587mvHxdFNCCm7I3/HzccKC3hYfKmSwRWf4rOqhVlz4yl6w9yIL3shHw6UsQ3agIpNYLkNAkFbMb5u0tb/2Eja+78Zg9JEN0SNSfmHaoQfD9BlYgKHA+B/TYmSG5B3RmVl8GAtnpPFJPwUErDClXbXZ918oCXqgX3d9YT9kt9o1adR763vHQD3IfAtHZ8Bg3ynwAUJCP1q3g5TfUmutMJGdlIjyrxFspMvij7b8rsNGHaBuUPKzKJTwFkf9chymhBjiXL8knogTyOk6GdFBa+8efoVVM/ou0ouBZHgGtp9bWTr9n4yDhz91xUHHFMuIXZuaBdgfUA41kWhkwy3rgZVQsZQPjmpjsw/vFv65Vrv3GaKzLzPjSG80MNbSsnX9/TgBsFAovXb1SxJJK0qMFaoWoCPDJWPwZoVpDOmfelI4BsmwNBJjjmXPsv1o+78qvNGXzs0SOJDdtTVZdEnS5OPak2e5Lo6k6QwQx8rTfxi8vt0HTA+wTY1oYNfiwM8eYzX+iigTOEPGi/NEO9ByeC/fKHaXXPB/hYs1gSwWnjj+9Bgze90meL8lmoeRwPiLTrfetVtTSYLa+6KPjhiYvIgxRgKpDnS1rp6IzNlW9PiCjeGJQI=}
