travis:
  secure:
    BINSTAR_TOKEN: p51QLZyDDyG61t7dpOLmt65r5PVTYMTAOeYZ4bTQ1NUOmiXsu61aCUIonR4eZTc+npXSJTXlPJh4ZBDN2E0h0TCT3Qwz6af7NykdnC8sLeuRNbbFl/Z9OuG8ZqRZrFmcSw0DhAE5SZCQlT/iPOzqvfY9UxfwM8aWJkvwlSm47GcFrQZKpLkbDffLCSCKEN7ann6B+HADEn8ClWaHZz50A/jj6H31ZaYJyXAIX5jG2Y1weeIfV80oF1JaIk6wa65c9L2A02g/QZi4Z1ndcUnD3CL9UugasYuiWw2O82SuAVbjBnPJ07B19uam5wN+PBYgVKfjDo9WVqEyu8lHjHsUzsZEUcINSsonuvstxexD3fcmd11G3VI4JD19uneA41hLjtja6zGh+FThxHkkxG3//woida0eUvgg9fub2KABkz2y1yhadhXHXF7Z8QvQ9wLiFlAWy2yjmPivqZm/a1hEbvRfzebRdR08YjFW6JzWe+KEUFKWvGL27Pqz9hIGSRWlxNte14NPW+0+7BIe4GqXg7YEMjZcfigatZ2/YXZNgy+tU7rgMfk9i50oFJGMbFxDxJbPu9DPMfDAdFjxNamcxwuAs+wkrExzr1grKtxiHgquD5jo6bbjn5ECTQmxDYVAwuyInxOQJRMvzUcO0BRuePFQVyxsB8P3c5KWMIuu4Gk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
